<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Re-Enter Password_password-reenter</name>
   <tag></tag>
   <elementGuidId>716f331a-275c-4c48-b091-a224651a9b7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#password-reenter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='password-reenter']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3cd702de-cd7d-4f04-b5b1-b0ce00373751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>6e1504fc-ed6e-4cf5-9679-c3fe78140a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Re-Enter Password</value>
      <webElementGuid>f39eb949-038a-4487-8605-ea3e0f661314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password-reenter</value>
      <webElementGuid>5a44e01e-3662-421c-bfb4-35c31b71ff96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>password-reenter</value>
      <webElementGuid>fe6496ad-39f1-4273-aa68-3cb3767608a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;password-reenter&quot;)</value>
      <webElementGuid>98cf7fd5-6d84-45fe-bb87-0bb7df2874c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='password-reenter']</value>
      <webElementGuid>d6a236ef-ea5a-4ef8-a533-5f43efc0bd2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registration-form']/input[3]</value>
      <webElementGuid>8d7f855c-2aea-4850-a0ae-25ef19ae07b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>4cf4b717-e670-4438-b7c9-26be5b33fbbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @placeholder = 'Re-Enter Password' and @name = 'password-reenter' and @id = 'password-reenter']</value>
      <webElementGuid>146de78b-cc8f-444d-9226-a1b5f51af3b2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
