<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>eroor</name>
   <tag></tag>
   <elementGuidId>cf1b4244-6025-484d-a88d-982f40d9363c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;loginForm&quot;)/span[@class=&quot;x1lliihq x1plvlek xryxfnj x1n2onr6 x193iq5w xeuugli x1fj9vlw x13faqbe x1vvkbs x1s928wv xhkezso x1gmr53x x1cpjm7i x1fgarty x1943h6x x1i0vuye xvs91rp xo1l8bm x5n08af x1tu3fi x3x7a5m x10wh9bi x1wdrske x8viiok x18hxmgj&quot;]/div[@class=&quot;_ab2z&quot;][count(. | //div[@class = '_ab2z' and (text() = 'Sorry, your password was incorrect. Please double-check your password.' or . = 'Sorry, your password was incorrect. Please double-check your password.')]) = count(//div[@class = '_ab2z' and (text() = 'Sorry, your password was incorrect. Please double-check your password.' or . = 'Sorry, your password was incorrect. Please double-check your password.')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._ab2z</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='loginForm']/span/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b3b2d085-18a9-409f-9c61-ed0d2c6ed41a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_ab2z</value>
      <webElementGuid>a368936b-1544-4606-9e65-675de253dc34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sorry, your password was incorrect. Please double-check your password.</value>
      <webElementGuid>3d4441e6-ce4d-48b2-ba91-8ededab31488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginForm&quot;)/span[@class=&quot;x1lliihq x1plvlek xryxfnj x1n2onr6 x193iq5w xeuugli x1fj9vlw x13faqbe x1vvkbs x1s928wv xhkezso x1gmr53x x1cpjm7i x1fgarty x1943h6x x1i0vuye xvs91rp xo1l8bm x5n08af x1tu3fi x3x7a5m x10wh9bi x1wdrske x8viiok x18hxmgj&quot;]/div[@class=&quot;_ab2z&quot;]</value>
      <webElementGuid>01ea0b55-3b69-478f-baff-a8c9e0f2ea3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginForm']/span/div</value>
      <webElementGuid>573888dc-1b9b-44b6-84a1-5c187350eaea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log in with Facebook'])[1]/following::div[1]</value>
      <webElementGuid>e0430b1b-51cb-4e1a-9bbc-efaa5fce1eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='or'])[1]/following::div[3]</value>
      <webElementGuid>6da4e3f8-b45d-4707-9103-3edc55277089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot password?'])[1]/preceding::div[1]</value>
      <webElementGuid>ef197771-d8c8-4518-9db4-4d8864210361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign up'])[1]/preceding::div[1]</value>
      <webElementGuid>0feba13a-8b26-4296-af52-26ba7d31b30c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sorry, your password was incorrect. Please double-check your password.']/parent::*</value>
      <webElementGuid>01432c22-dfad-4e8b-8eef-161c0532e5bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/div</value>
      <webElementGuid>a71c91e9-b725-4813-ae35-123e383543d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sorry, your password was incorrect. Please double-check your password.' or . = 'Sorry, your password was incorrect. Please double-check your password.')]</value>
      <webElementGuid>b8eb053d-357a-44dd-8040-2a7a2b4f0034</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
