<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Images</name>
   <tag></tag>
   <elementGuidId>2e5323d8-fe60-417c-aec7-239d8580123c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='bqHHPb']/div/div/div/div/div/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.GKS7s</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>07ab0153-ac1e-4bd8-ba1f-c9cc9b702391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>bVqjv</value>
      <webElementGuid>dd189fd3-8538-406c-bf26-f74167da417f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GKS7s</value>
      <webElementGuid>1c6bbd37-7f63-45f3-88dc-f687b7af2959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Images</value>
      <webElementGuid>ca3ca656-9ea7-487f-b463-83871aaef14e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;bqHHPb&quot;)/div[@class=&quot;fMHynf Jb8vdb&quot;]/div[@class=&quot;X8DMoe&quot;]/div[@class=&quot;zp6Lyf&quot;]/div[@class=&quot;IUOThf&quot;]/div[1]/a[@class=&quot;LatpMc nPDzT T3FoJb&quot;]/div[@class=&quot;GKS7s&quot;]</value>
      <webElementGuid>351886c6-757a-4444-96e6-210a13a54d47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='bqHHPb']/div/div/div/div/div/a/div</value>
      <webElementGuid>480292fb-f7bf-455f-9f09-1b74f00d256a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Filters and Topics'])[1]/following::div[5]</value>
      <webElementGuid>ee6365f2-f0ed-44cf-9f7f-938046a650f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/following::div[22]</value>
      <webElementGuid>accd8910-463e-4398-a710-973fb024333a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='News'])[1]/preceding::div[1]</value>
      <webElementGuid>54154af8-6d11-45f4-8fc5-d92290f4339b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/div</value>
      <webElementGuid>bbcafafe-8e71-4336-b38c-13188d4f09ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Images' or . = 'Images')]</value>
      <webElementGuid>c8a5e0bf-93c7-435a-851a-4f555eed087f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
