<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Books</name>
   <tag></tag>
   <elementGuidId>e2a5dafd-d44e-4466-ad70-1b45db7767b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='L6jfZfe4Bq_BkPIPgfumsAI__11']/div/a/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#L6jfZfe4Bq_BkPIPgfumsAI__11 > div > a.LatpMc.nPDzT.T3FoJb > div.GKS7s</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8bb07cb1-3bcb-4c48-aace-2b54bf884108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>jsname</name>
      <type>Main</type>
      <value>bVqjv</value>
      <webElementGuid>20f09126-f28c-407d-8dc2-13e4be121cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>GKS7s</value>
      <webElementGuid>b8933567-73d7-4ac8-adcd-1c8c62ded56d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Books</value>
      <webElementGuid>c98950e8-ccae-44c2-a5ba-26f55d54e36a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;L6jfZfe4Bq_BkPIPgfumsAI__11&quot;)/div[1]/a[@class=&quot;LatpMc nPDzT T3FoJb&quot;]/div[@class=&quot;GKS7s&quot;]</value>
      <webElementGuid>db1efbac-6fba-4c81-b67a-ded654389f66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='L6jfZfe4Bq_BkPIPgfumsAI__11']/div/a/div</value>
      <webElementGuid>a836b1e0-677c-42b0-9240-a2d7f82ea278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maps'])[1]/following::div[3]</value>
      <webElementGuid>e25897ed-8ef3-4036-85e2-4e7d5a3eabe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Footage'])[1]/following::div[6]</value>
      <webElementGuid>22c4b0bf-08d4-495c-8d8e-2483aab194f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All filters'])[1]/preceding::div[4]</value>
      <webElementGuid>5226e5de-4e7f-4f65-8bf3-3623182f4d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/a/div</value>
      <webElementGuid>e1484677-4bd3-4efd-beb6-64cb25887ede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Books' or . = 'Books')]</value>
      <webElementGuid>98702368-5d24-433a-9569-20ac46e35c6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
