<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_We can save your login info on this browser so you dont need to enter it again</name>
   <tag></tag>
   <elementGuidId>b993472b-60f3-40fc-9d29-dc6acc66b655</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mount_0_0_X8']/div/div/div[2]/div/div/div/div/div[2]/section/main/div/div/div/section/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._aa59</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f52dabd2-5351-48de-820e-e0ca7c35e357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_aa59</value>
      <webElementGuid>f144eea7-9bf6-4ac3-9226-0fcaf508303f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>We can save your login info on this browser so you don't need to enter it again.</value>
      <webElementGuid>20ad9380-9d94-4693-9e53-c2b7f4a7c15e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mount_0_0_X8&quot;)/div[1]/div[1]/div[@class=&quot;x9f619 x1n2onr6 x1ja2u2z&quot;]/div[@class=&quot;x78zum5 xdt5ytf x1n2onr6 x1ja2u2z&quot;]/div[@class=&quot;x78zum5 xdt5ytf x1n2onr6 xat3117 xxzkxad&quot;]/div[@class=&quot;x78zum5 xdt5ytf x1t2pt76 x1n2onr6 x1ja2u2z x10cihs4&quot;]/div[@class=&quot;x9f619 xvbhtw8 x78zum5 x168nmei x13lgxp2 x5pf9jr xo71vjh x1uhb9sk x1plvlek xryxfnj x1c4vz4f x2lah0s x1q0g3np xqjyukv x1qjc9v5 x1oa3qoh x1qughib&quot;]/div[@class=&quot;x1gryazu xh8yej3 x10o80wk x14k21rp x17snn68 x6osk4m x1porb0y&quot;]/section[@class=&quot;x78zum5 xdt5ytf x1iyjqo2 x6ikm8r xg6iff7&quot;]/main[@class=&quot;xvbhtw8 x78zum5 xdt5ytf x1iyjqo2 x182iqb8&quot;]/div[@class=&quot;x9f619 xjbqb8w x78zum5 x168nmei x13lgxp2 x5pf9jr xo71vjh x1n2onr6 x1plvlek xryxfnj x1iyjqo2 x2lwn1j xeuugli xdt5ytf xqjyukv x6s0dn4 x1oa3qoh xl56j7k&quot;]/div[@class=&quot;x9f619 xvbhtw8 x78zum5 x5ur3kl xopu45v x1bs97v6 xmo9t06 x13fuv20 xu3j5b3 x1q0q8m5 x26u7qi x178xt8z xm81vs4 xso031l xy80clv x168nmei x13lgxp2 x5pf9jr xo71vjh x1n2onr6 x1plvlek xryxfnj x1c4vz4f x2lah0s xdt5ytf xqjyukv x1qjc9v5 x1oa3qoh x1nhvcw1&quot;]/div[@class=&quot;x9f619 xjbqb8w x78zum5 x168nmei x13lgxp2 x5pf9jr xo71vjh xw7yly9 x1yztbdb x1n2onr6 x1plvlek xryxfnj x1c4vz4f x2lah0s xdt5ytf xqjyukv x1qjc9v5 x1oa3qoh x1nhvcw1&quot;]/section[@class=&quot;_aa55&quot;]/div[@class=&quot;_aa56&quot;]/div[@class=&quot;_aa59&quot;]</value>
      <webElementGuid>3b4d4207-7934-4106-8c6c-21a7c70f3cfa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mount_0_0_X8']/div/div/div[2]/div/div/div/div/div[2]/section/main/div/div/div/section/div/div[3]</value>
      <webElementGuid>0dfa647e-2228-4450-8b65-bb40ec5b28b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save your login info?'])[1]/following::div[1]</value>
      <webElementGuid>757fca10-dc71-46e8-a8f7-86eae8a4e311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[1]/following::div[8]</value>
      <webElementGuid>e76d4650-b435-4351-b011-f48b2ac14e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save info'])[1]/preceding::div[1]</value>
      <webElementGuid>1c138c19-5d29-4363-a0e0-0bc2f85a6e04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not now'])[1]/preceding::div[1]</value>
      <webElementGuid>e64bbc9e-3e7f-4ab8-9dd7-de7aa64a8ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div[3]</value>
      <webElementGuid>20831c61-22a7-4457-b9eb-0286d686a2ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;We can save your login info on this browser so you don&quot; , &quot;'&quot; , &quot;t need to enter it again.&quot;) or . = concat(&quot;We can save your login info on this browser so you don&quot; , &quot;'&quot; , &quot;t need to enter it again.&quot;))]</value>
      <webElementGuid>364753bf-41a9-4a0a-bc36-825beb2d6300</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
