<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>loginInfo</name>
   <tag></tag>
   <elementGuidId>b993472b-60f3-40fc-9d29-dc6acc66b655</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class = '_aa59' and (contains(text(), concat(&quot;We can save your login info on this browser so you don&quot; , &quot;'&quot; , &quot;t need to enter it again.&quot;)) or contains(., concat(&quot;We can save your login info on this browser so you don&quot; , &quot;'&quot; , &quot;t need to enter it again.&quot;)))]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div._aa59</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mount_0_0_X8']/div/div/div[2]/div/div/div/div/div[2]/section/main/div/div/div/section/div/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6edbf225-d510-4ccd-adc6-c8a8769ea0af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_aa59</value>
      <webElementGuid>8c997522-190b-4aea-a34b-8470fb39c5bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mount_0_0_X8&quot;)/div[1]/div[1]/div[@class=&quot;x9f619 x1n2onr6 x1ja2u2z&quot;]/div[@class=&quot;x78zum5 xdt5ytf x1n2onr6 x1ja2u2z&quot;]/div[@class=&quot;x78zum5 xdt5ytf x1n2onr6 xat3117 xxzkxad&quot;]/div[@class=&quot;x78zum5 xdt5ytf x1t2pt76 x1n2onr6 x1ja2u2z x10cihs4&quot;]/div[@class=&quot;x9f619 xvbhtw8 x78zum5 x168nmei x13lgxp2 x5pf9jr xo71vjh x1uhb9sk x1plvlek xryxfnj x1c4vz4f x2lah0s x1q0g3np xqjyukv x1qjc9v5 x1oa3qoh x1qughib&quot;]/div[@class=&quot;x1gryazu xh8yej3 x10o80wk x14k21rp x17snn68 x6osk4m x1porb0y&quot;]/section[@class=&quot;x78zum5 xdt5ytf x1iyjqo2 x6ikm8r xg6iff7&quot;]/main[@class=&quot;xvbhtw8 x78zum5 xdt5ytf x1iyjqo2 x182iqb8&quot;]/div[@class=&quot;x9f619 xjbqb8w x78zum5 x168nmei x13lgxp2 x5pf9jr xo71vjh x1n2onr6 x1plvlek xryxfnj x1iyjqo2 x2lwn1j xeuugli xdt5ytf xqjyukv x6s0dn4 x1oa3qoh xl56j7k&quot;]/div[@class=&quot;x9f619 xvbhtw8 x78zum5 x5ur3kl xopu45v x1bs97v6 xmo9t06 x13fuv20 xu3j5b3 x1q0q8m5 x26u7qi x178xt8z xm81vs4 xso031l xy80clv x168nmei x13lgxp2 x5pf9jr xo71vjh x1n2onr6 x1plvlek xryxfnj x1c4vz4f x2lah0s xdt5ytf xqjyukv x1qjc9v5 x1oa3qoh x1nhvcw1&quot;]/div[@class=&quot;x9f619 xjbqb8w x78zum5 x168nmei x13lgxp2 x5pf9jr xo71vjh xw7yly9 x1yztbdb x1n2onr6 x1plvlek xryxfnj x1c4vz4f x2lah0s xdt5ytf xqjyukv x1qjc9v5 x1oa3qoh x1nhvcw1&quot;]/section[@class=&quot;_aa55&quot;]/div[@class=&quot;_aa56&quot;]/div[@class=&quot;_aa59&quot;]</value>
      <webElementGuid>5fd3b73e-6754-4dcb-a4b4-df3b0bad606c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>We can save your login info on this browser so you don't need to enter it again.</value>
      <webElementGuid>b3dae007-31ce-46bc-b4f6-088a7c6fd8a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mount_0_0_X8']/div/div/div[2]/div/div/div/div/div[2]/section/main/div/div/div/section/div/div[3]</value>
      <webElementGuid>04846f58-ddab-4648-8601-3273c246fa5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save your login info?'])[1]/following::div[1]</value>
      <webElementGuid>1c9676bd-e2f4-4198-8fef-4cb4ff34c591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[1]/following::div[8]</value>
      <webElementGuid>a94f34c3-7595-418c-b445-f37696597421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save info'])[1]/preceding::div[1]</value>
      <webElementGuid>6d4d9081-d8a5-494c-aa0f-7a524bb994e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Not now'])[1]/preceding::div[1]</value>
      <webElementGuid>40f9159a-914d-4147-865b-0cfdb309b0a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div[3]</value>
      <webElementGuid>4c8e26db-4560-4086-984e-cfd60ba8c864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;We can save your login info on this browser so you don&quot; , &quot;'&quot; , &quot;t need to enter it again.&quot;) or . = concat(&quot;We can save your login info on this browser so you don&quot; , &quot;'&quot; , &quot;t need to enter it again.&quot;))]</value>
      <webElementGuid>0c44c656-f7a5-42e6-9de7-5f7c50393b00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
